In [ ]:
!pip -q install feast==0.64.0 pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 66.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 20.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 12.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 79.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 51.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 30.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 3.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.

In [ ]:
import feast

print("Feast version:", feast.__version__)

Feast version: 0.64.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving cse_curriculum_industry_skill_alignment_1500.csv to cse_curriculum_industry_skill_alignment_1500.csv

In [ ]:
import pandas as pd

df = pd.read_csv(
    "cse_curriculum_industry_skill_alignment_1500.csv"
)

print(df.head())
print("Dataset shape:", df.shape)

  student_id         university  gender  graduation_year         target_role  \
0    STU0001  Andhra University    Male             2027      Cloud Engineer
1    STU0002      KL University    Male             2025  Software Developer
2    STU0003      JNTU Kakinada  Female             2025     DevOps Engineer
3    STU0004   GITAM University    Male             2025  Software Developer
4    STU0005   GITAM University    Male             2025  Software Developer

   cgpa  attendance_percent  internship_count  project_count  \
0  6.71                84.9                 0              1
1  8.08                76.6                 2              3
2  8.07                90.0                 2              4
3  7.87                82.8                 2              2
4  7.33                74.8                 3              2

   certification_count  ...  communication_gap  \
0                  2.0  ...               11.0
1                  NaN  ...                7.2
2                  0.0  ...                0.0
3                  1.0  ...               17.2
4                  1.0  ...                0.0

  curriculum_problem_solving_score  industry_problem_solving_required  \
0                             37.1                                 76
1                             62.8                                 78
2                             74.9                                 80
3                             48.8                                 78
4                             91.2                                 78

   problem_solving_gap  overall_skill_alignment  average_skill_gap  \
0                 38.9                    81.57              18.43
1                 15.2                    95.39               4.61
2                  5.1                    98.75               1.25
3                 29.2                    89.87              10.13
4                  0.0                    98.31               1.69

   employability_score  skill_gap_category  placement_status  \
0                59.26        Moderate Gap        Not Placed
1                81.67             Low Gap            Placed
2                86.93             Low Gap            Placed
3                77.98        Moderate Gap            Placed
4                90.52             Low Gap            Placed

       event_timestamp
0  2026-05-20 00:00:00
1  2025-08-05 00:00:00
2  2026-01-28 00:00:00
3  2025-09-16 00:00:00
4  2025-07-17 00:00:00

[5 rows x 48 columns]
Dataset shape: (1500, 48)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
print(df.columns.tolist())

df.info()

print("\nMissing values:")
print(df.isnull().sum())

['student_id', 'university', 'gender', 'graduation_year', 'target_role', 'cgpa', 'attendance_percent', 'internship_count', 'project_count', 'certification_count', 'hackathon_count', 'programming_language', 'curriculum_programming_score', 'industry_programming_required', 'programming_gap', 'curriculum_dsa_score', 'industry_dsa_required', 'dsa_gap', 'curriculum_dbms_score', 'industry_dbms_required', 'dbms_gap', 'curriculum_web_development_score', 'industry_web_development_required', 'web_development_gap', 'curriculum_cloud_score', 'industry_cloud_required', 'cloud_gap', 'curriculum_ai_ml_score', 'industry_ai_ml_required', 'ai_ml_gap', 'curriculum_cybersecurity_score', 'industry_cybersecurity_required', 'cybersecurity_gap', 'curriculum_devops_score', 'industry_devops_required', 'devops_gap', 'curriculum_communication_score', 'industry_communication_required', 'communication_gap', 'curriculum_problem_solving_score', 'industry_problem_solving_required', 'problem_solving_gap', 'overall_skill_alignment', 'average_skill_gap', 'employability_score', 'skill_gap_category', 'placement_status', 'event_timestamp']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 48 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   student_id                         1500 non-null   object
 1   university                         1500 non-null   object
 2   gender                             1500 non-null   object
 3   graduation_year                    1500 non-null   int64
 4   target_role                        1500 non-null   object
 5   cgpa                               1462 non-null   float64
 6   attendance_percent                 1462 non-null   float64
 7   internship_count                   1500 non-null   int64
 8   project_count                      1500 non-null   int64
 9   certification_count                1462 non-null   float64
 10  hackathon_count                    1500 non-null   int64
 11  programming_language               1500 non-null   object
 12  curriculum_programming_score       1500 non-null   float64
 13  industry_programming_required      1500 non-null   int64
 14  programming_gap                    1500 non-null   float64
 15  curriculum_dsa_score               1500 non-null   float64
 16  industry_dsa_required              1500 non-null   int64
 17  dsa_gap                            1500 non-null   float64
 18  curriculum_dbms_score              1500 non-null   float64
 19  industry_dbms_required             1500 non-null   int64
 20  dbms_gap                           1500 non-null   float64
 21  curriculum_web_development_score   1500 non-null   float64
 22  industry_web_development_required  1500 non-null   int64
 23  web_development_gap                1500 non-null   float64
 24  curriculum_cloud_score             1462 non-null   float64
 25  industry_cloud_required            1500 non-null   int64
 26  cloud_gap                          1500 non-null   float64
 27  curriculum_ai_ml_score             1462 non-null   float64
 28  industry_ai_ml_required            1500 non-null   int64
 29  ai_ml_gap                          1500 non-null   float64
 30  curriculum_cybersecurity_score     1500 non-null   float64
 31  industry_cybersecurity_required    1500 non-null   int64
 32  cybersecurity_gap                  1500 non-null   float64
 33  curriculum_devops_score            1500 non-null   float64
 34  industry_devops_required           1500 non-null   int64
 35  devops_gap                         1500 non-null   float64
 36  curriculum_communication_score     1462 non-null   float64
 37  industry_communication_required    1500 non-null   int64
 38  communication_gap                  1500 non-null   float64
 39  curriculum_problem_solving_score   1500 non-null   float64
 40  industry_problem_solving_required  1500 non-null   int64
 41  problem_solving_gap                1500 non-null   float64
 42  overall_skill_alignment            1500 non-null   float64
 43  average_skill_gap                  1500 non-null   float64
 44  employability_score                1500 non-null   float64
 45  skill_gap_category                 1500 non-null   object
 46  placement_status                   1500 non-null   object
 47  event_timestamp                    1500 non-null   object
dtypes: float64(26), int64(14), object(8)
memory usage: 562.6+ KB

Missing values:
student_id                            0
university                            0
gender                                0
graduation_year                       0
target_role                           0
cgpa                                 38
attendance_percent                   38
internship_count                      0
project_count                         0
certification_count                  38
hackathon_count                       0
programming_language                  0
curriculum_programming_score          0
industry_programming_required         0
programming_gap                       0
curriculum_dsa_score                  0
industry_dsa_required                 0
dsa_gap                               0
curriculum_dbms_score                 0
industry_dbms_required                0
dbms_gap                              0
curriculum_web_development_score      0
industry_web_development_required     0
web_development_gap                   0
curriculum_cloud_score               38
industry_cloud_required               0
cloud_gap                             0
curriculum_ai_ml_score               38
industry_ai_ml_required               0
ai_ml_gap                             0
curriculum_cybersecurity_score        0
industry_cybersecurity_required       0
cybersecurity_gap                     0
curriculum_devops_score               0
industry_devops_required              0
devops_gap                            0
curriculum_communication_score       38
industry_communication_required       0
communication_gap                     0
curriculum_problem_solving_score      0
industry_problem_solving_required     0
problem_solving_gap                   0
overall_skill_alignment               0
average_skill_gap                     0
employability_score                   0
skill_gap_category                    0
placement_status                      0
event_timestamp                       0
dtype: int64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# -----------------------------
# ENTITY
# -----------------------------

df["student_id"] = df["student_id"].astype(str)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
numeric_feast_columns = [
    "cgpa",
    "attendance_percent",
    "internship_count",
    "project_count",
    "certification_count",
    "hackathon_count",
    "curriculum_programming_score",
    "curriculum_dsa_score",
    "curriculum_dbms_score",
    "curriculum_web_development_score",
    "curriculum_cloud_score",
    "curriculum_ai_ml_score",
    "curriculum_cybersecurity_score",
    "curriculum_devops_score",
    "curriculum_communication_score",
    "curriculum_problem_solving_score",
    "overall_skill_alignment",
    "average_skill_gap",
    "employability_score"
]

for column in numeric_feast_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

    df[column] = df[column].fillna(
        df[column].median()
    )

In [ ]:
df["target_role_encoded"] = (
    df["target_role"]
    .astype("category")
    .cat.codes
    .astype("int64")
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
df["university_encoded"] = (
    df["university"]
    .astype("category")
    .cat.codes
    .astype("int64")
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
df["programming_language_encoded"] = (
    df["programming_language"]
    .astype("category")
    .cat.codes
    .astype("int64")
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
df["gender_encoded"] = (
    df["gender"]
    .astype("category")
    .cat.codes
    .astype("int64")
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
df["total_experience"] = (
    df["internship_count"]
    + df["project_count"]
    + df["hackathon_count"]
).astype("int64")

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
skill_columns = [
    "curriculum_programming_score",
    "curriculum_dsa_score",
    "curriculum_dbms_score",
    "curriculum_web_development_score",
    "curriculum_cloud_score",
    "curriculum_ai_ml_score",
    "curriculum_cybersecurity_score",
    "curriculum_devops_score",
    "curriculum_communication_score",
    "curriculum_problem_solving_score"
]

df["average_curriculum_skill"] = (
    df[skill_columns].mean(axis=1)
).astype("float32")

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
df["event_timestamp"] = pd.to_datetime(
    df["event_timestamp"],
    utc=True
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
df["created_timestamp"] = (
    df["event_timestamp"]
    + pd.Timedelta(seconds=1)
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
feature_df = df[
    [
        "student_id",
        "event_timestamp",
        "created_timestamp",

        "cgpa",
        "attendance_percent",
        "internship_count",
        "project_count",
        "certification_count",
        "hackathon_count",

        "curriculum_programming_score",
        "curriculum_dsa_score",
        "curriculum_dbms_score",
        "curriculum_web_development_score",
        "curriculum_cloud_score",
        "curriculum_ai_ml_score",
        "curriculum_cybersecurity_score",
        "curriculum_devops_score",
        "curriculum_communication_score",
        "curriculum_problem_solving_score",

        "overall_skill_alignment",
        "average_skill_gap",
        "employability_score",

        "university_encoded",
        "gender_encoded",
        "target_role_encoded",
        "programming_language_encoded",

        "total_experience",
        "average_curriculum_skill"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
label_df = df[
    [
        "student_id",
        "event_timestamp",
        "placement_status"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
label_df["placed"] = (
    label_df["placement_status"]
    .map({
        "Not Placed": 0,
        "Placed": 1
    })
    .astype("int64")
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
label_df = label_df[
    [
        "student_id",
        "event_timestamp",
        "placed"
    ]
]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
print("Feature data:")
display(feature_df.head())

print("Labels:")
display(label_df.head())

Feature data:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,event_timestamp,created_timestamp,cgpa,attendance_percent,internship_count,project_count,certification_count,hackathon_count,curriculum_programming_score,...,curriculum_problem_solving_score,overall_skill_alignment,average_skill_gap,employability_score,university_encoded,gender_encoded,target_role_encoded,programming_language_encoded,total_experience,average_curriculum_skill
0,STU0001,2026-05-20 00:00:00+00:00,2026-05-20 00:00:01+00:00,6.71,84.9,0,1,2.0,1,56.6,...,37.1,81.57,18.43,59.26,0,1,0,3,2,53.490002
1,STU0002,2025-08-05 00:00:00+00:00,2025-08-05 00:00:01+00:00,8.08,76.6,2,3,1.0,1,75.6,...,62.8,95.39,4.61,81.67,3,1,5,4,6,70.820000
2,STU0003,2026-01-28 00:00:00+00:00,2026-01-28 00:00:01+00:00,8.07,90.0,2,4,0.0,0,65.5,...,74.9,98.75,1.25,86.93,2,0,3,0,6,81.620003
3,STU0004,2025-09-16 00:00:00+00:00,2025-09-16 00:00:01+00:00,7.87,82.8,2,2,1.0,1,54.2,...,48.8,89.87,10.13,77.98,1,1,5,3,5,68.480003
4,STU0005,2025-07-17 00:00:00+00:00,2025-07-17 00:00:01+00:00,7.33,74.8,3,2,1.0,1,81.2,...,91.2,98.31,1.69,90.52,1,1,5,4,6,80.930000

Labels:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

  student_id           event_timestamp  placed
0    STU0001 2026-05-20 00:00:00+00:00       0
1    STU0002 2025-08-05 00:00:00+00:00       1
2    STU0003 2026-01-28 00:00:00+00:00       1
3    STU0004 2025-09-16 00:00:00+00:00       1
4    STU0005 2025-07-17 00:00:00+00:00       1

In [ ]:
import os

repo_path = "/content/cse_employability_feast"

os.makedirs(
    f"{repo_path}/data",
    exist_ok=True
)

print("Repository created:", repo_path)

Repository created: /content/cse_employability_feast

In [ ]:
feature_df.to_parquet(
    f"{repo_path}/data/student_features.parquet",
    index=False
)

print("Feature parquet file created.")

Feature parquet file created.

In [ ]:
feature_store_yaml = """
project: cse_employability_project

registry: data/registry.db

provider: local

offline_store:
  type: file

online_store:
  type: sqlite
  path: data/online_store.db
"""

with open(
    f"{repo_path}/feature_store.yaml",
    "w"
) as f:
    f.write(feature_store_yaml)

print("feature_store.yaml created.")

feature_store.yaml created.

In [ ]:
feature_definition = '''
from datetime import timedelta

from feast import (
    Entity,
    FeatureView,
    FeatureService,
    Field,
    FileSource
)

from feast.types import (
    Float32,
    Int64
)


# -----------------------------
# ENTITY
# -----------------------------

student = Entity(
    name="student",
    join_keys=["student_id"],
    description="CSE student for employability skill analysis"
)


# -----------------------------
# DATA SOURCE
# -----------------------------

student_source = FileSource(
    name="student_source",
    path="data/student_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp"
)


# -----------------------------
# FEATURE VIEW
# -----------------------------

student_feature_view = FeatureView(
    name="student_employability_features",

    entities=[student],

    ttl=timedelta(days=3650),

    schema=[
        Field(name="cgpa", dtype=Float32),
        Field(name="attendance_percent", dtype=Float32),

        Field(name="internship_count", dtype=Int64),
        Field(name="project_count", dtype=Int64),
        Field(name="certification_count", dtype=Int64),
        Field(name="hackathon_count", dtype=Int64),

        Field(
            name="curriculum_programming_score",
            dtype=Float32
        ),

        Field(
            name="curriculum_dsa_score",
            dtype=Float32
        ),

        Field(
            name="curriculum_dbms_score",
            dtype=Float32
        ),

        Field(
            name="curriculum_web_development_score",
            dtype=Float32
        ),

        Field(
            name="curriculum_cloud_score",
            dtype=Float32
        ),

        Field(
            name="curriculum_ai_ml_score",
            dtype=Float32
        ),

        Field(
            name="curriculum_cybersecurity_score",
            dtype=Float32
        ),

        Field(
            name="curriculum_devops_score",
            dtype=Float32
        ),

        Field(
            name="curriculum_communication_score",
            dtype=Float32
        ),

        Field(
            name="curriculum_problem_solving_score",
            dtype=Float32
        ),

        Field(
            name="overall_skill_alignment",
            dtype=Float32
        ),

        Field(
            name="average_skill_gap",
            dtype=Float32
        ),

        Field(
            name="employability_score",
            dtype=Float32
        ),

        Field(
            name="university_encoded",
            dtype=Int64
        ),

        Field(
            name="gender_encoded",
            dtype=Int64
        ),

        Field(
            name="target_role_encoded",
            dtype=Int64
        ),

        Field(
            name="programming_language_encoded",
            dtype=Int64
        ),

        Field(
            name="total_experience",
            dtype=Int64
        ),

        Field(
            name="average_curriculum_skill",
            dtype=Float32
        ),
    ],

    source=student_source,

    online=True
)


# -----------------------------
# FEATURE SERVICE
# -----------------------------

student_feature_service = FeatureService(
    name="cse_employability_service",

    features=[
        student_feature_view
    ]
)
'''

with open(
    f"{repo_path}/features.py",
    "w"
) as f:
    f.write(feature_definition)

print("features.py created successfully.")

features.py created successfully.

In [ ]:
!find /content/cse_employability_feast -maxdepth 2 -type f

/content/cse_employability_feast/feature_store.yaml
/content/cse_employability_feast/data/student_features.parquet
/content/cse_employability_feast/features.py

In [ ]:
%cd /content/cse_employability_feast

/content/cse_employability_feast

In [ ]:
!feast apply

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/cse_employability_feast/features.py:22: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student'.
  student = Entity(
No project found in the repository. Using project name cse_employability_project defined in feature_store.yaml
Applying changes for project cse_employability_project
Created project cse_employability_project
Created entity student
Created feature view student_employability_features
Created feature service cse_employability_service

Created sqlite table cse_employability_project_student_employability_features

In [ ]:
!feast entities list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME     DESCRIPTION                                   TYPE
student  CSE student for employability skill analysis  ValueType.UNKNOWN

In [ ]:
!feast feature-views list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME                            ENTITIES     TYPE         ENABLED    STATE
student_employability_features  {'student'}  FeatureView  Yes        STATE_UNSPECIFIED

In [ ]:
from feast import FeatureStore

store = FeatureStore(
    repo_path="/content/cse_employability_feast"
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
feature_service = store.get_feature_service(
    "cse_employability_service"
)

print(feature_service)

{
  "spec": {
    "name": "cse_employability_service",
    "features": [
      {
        "featureViewName": "student_employability_features",
        "featureColumns": [
          {
            "name": "cgpa",
            "valueType": "FLOAT"
          },
          {
            "name": "attendance_percent",
            "valueType": "FLOAT"
          },
          {
            "name": "internship_count",
            "valueType": "INT64"
          },
          {
            "name": "project_count",
            "valueType": "INT64"
          },
          {
            "name": "certification_count",
            "valueType": "INT64"
          },
          {
            "name": "hackathon_count",
            "valueType": "INT64"
          },
          {
            "name": "curriculum_programming_score",
            "valueType": "FLOAT"
          },
          {
            "name": "curriculum_dsa_score",
            "valueType": "FLOAT"
          },
          {
            "name": "curriculum_dbms_score",
            "valueType": "FLOAT"
          },
          {
            "name": "curriculum_web_development_score",
            "valueType": "FLOAT"
          },
          {
            "name": "curriculum_cloud_score",
            "valueType": "FLOAT"
          },
          {
            "name": "curriculum_ai_ml_score",
            "valueType": "FLOAT"
          },
          {
            "name": "curriculum_cybersecurity_score",
            "valueType": "FLOAT"
          },
          {
            "name": "curriculum_devops_score",
            "valueType": "FLOAT"
          },
          {
            "name": "curriculum_communication_score",
            "valueType": "FLOAT"
          },
          {
            "name": "curriculum_problem_solving_score",
            "valueType": "FLOAT"
          },
          {
            "name": "overall_skill_alignment",
            "valueType": "FLOAT"
          },
          {
            "name": "average_skill_gap",
            "valueType": "FLOAT"
          },
          {
            "name": "employability_score",
            "valueType": "FLOAT"
          },
          {
            "name": "university_encoded",
            "valueType": "INT64"
          },
          {
            "name": "gender_encoded",
            "valueType": "INT64"
          },
          {
            "name": "target_role_encoded",
            "valueType": "INT64"
          },
          {
            "name": "programming_language_encoded",
            "valueType": "INT64"
          },
          {
            "name": "total_experience",
            "valueType": "INT64"
          },
          {
            "name": "average_curriculum_skill",
            "valueType": "FLOAT"
          }
        ],
        "timestampField": "created_timestamp",
        "createdTimestampColumn": "created_timestamp",
        "batchSource": {
          "type": "BATCH_FILE",
          "timestampField": "event_timestamp",
          "createdTimestampColumn": "created_timestamp",
          "fileOptions": {
            "uri": "data/student_features.parquet"
          },
          "name": "student_source",
          "meta": {
            "createdTimestamp": "2026-08-11T16:09:42.413108Z",
            "lastUpdatedTimestamp": "2026-08-11T16:09:42.484487Z"
          }
        },
        "viewType": "featureView"
      }
    ]
  },
  "meta": {
    "createdTimestamp": "2026-08-11T16:09:42.488059Z",
    "lastUpdatedTimestamp": "2026-08-11T16:09:42.488059Z"
  }
}

In [ ]:
entity_df = label_df[
    [
        "student_id",
        "event_timestamp",
        "placed"
    ]
].copy()

display(entity_df.head())

  student_id           event_timestamp  placed
0    STU0001 2026-05-20 00:00:00+00:00       0
1    STU0002 2025-08-05 00:00:00+00:00       1
2    STU0003 2026-01-28 00:00:00+00:00       1
3    STU0004 2025-09-16 00:00:00+00:00       1
4    STU0005 2025-07-17 00:00:00+00:00       1

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
training_data = store.get_historical_features(
    entity_df=entity_df,
    features=feature_service
).to_df()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
display(training_data.head())

,student_id,event_timestamp,placed,cgpa,attendance_percent,internship_count,project_count,certification_count,hackathon_count,curriculum_programming_score,...,curriculum_problem_solving_score,overall_skill_alignment,average_skill_gap,employability_score,university_encoded,gender_encoded,target_role_encoded,programming_language_encoded,total_experience,average_curriculum_skill
0,STU0570,2025-01-01 00:00:00+00:00,1,6.49,86.4,1,3,2.0,0,68.5,...,51.3,92.47,7.53,75.13,0,1,3,4,4,65.070000
1,STU0052,2025-01-02 00:00:00+00:00,1,9.55,79.6,2,1,3.0,1,98.0,...,92.2,100.00,0.00,89.06,5,1,3,4,4,86.879997
2,STU1461,2025-01-02 00:00:00+00:00,1,8.33,91.3,3,2,0.0,0,86.0,...,76.0,99.37,0.63,88.62,0,1,0,3,5,83.019997
3,STU1185,2025-01-02 00:00:00+00:00,1,6.81,84.1,0,3,2.0,1,71.9,...,71.6,91.30,8.70,71.34,4,0,4,3,4,65.830002
4,STU0902,2025-01-02 00:00:00+00:00,1,7.00,94.7,1,5,2.0,0,51.3,...,58.3,91.87,8.13,80.95,4,1,5,0,6,72.040001

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
print(
    "Historical training data shape:",
    training_data.shape
)

Historical training data shape: (1500, 28)

In [ ]:
feature_columns = [
    "cgpa",
    "attendance_percent",
    "internship_count",
    "project_count",
    "certification_count",
    "hackathon_count",

    "curriculum_programming_score",
    "curriculum_dsa_score",
    "curriculum_dbms_score",
    "curriculum_web_development_score",
    "curriculum_cloud_score",
    "curriculum_ai_ml_score",
    "curriculum_cybersecurity_score",
    "curriculum_devops_score",
    "curriculum_communication_score",
    "curriculum_problem_solving_score",

    "overall_skill_alignment",
    "average_skill_gap",
    "employability_score",

    "university_encoded",
    "gender_encoded",
    "target_role_encoded",
    "programming_language_encoded",

    "total_experience",
    "average_curriculum_skill"
]

In [ ]:
X = training_data[
    feature_columns
]

y = training_data[
    "placed"
]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1500, 25)
y shape: (1500,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [ ]:
predictions = model.predict(
    X_test
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    predictions
)

print(
    "Accuracy:",
    round(accuracy * 100, 2),
    "%"
)

Accuracy: 81.67 %

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
print(
    feature_df["event_timestamp"].min()
)

print(
    feature_df["event_timestamp"].max()
)

2025-01-01 00:00:00+00:00
2026-08-03 00:00:00+00:00

In [ ]:
start_time = feature_df["event_timestamp"].min()
end_time = feature_df["event_timestamp"].max()

print("Start:", start_time)
print("End:", end_time)

Start: 2025-01-01 00:00:00+00:00
End: 2026-08-03 00:00:00+00:00

In [ ]:
start_str = start_time.strftime(
    "%Y-%m-%dT%H:%M:%S"
)

end_str = end_time.strftime(
    "%Y-%m-%dT%H:%M:%S"
)

print(start_str)
print(end_str)

2025-01-01T00:00:00
2026-08-03T00:00:00

In [ ]:
!feast materialize {start_str} {end_str}

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Materializing 1 feature views from 2025-01-01 00:00:00+00:00 to 2026-08-03 00:00:00+00:00 into the sqlite online store.

student_employability_features:

In [ ]:
online_features = store.get_online_features(
    features=feature_service,
    entity_rows=[
        {
            "student_id": "STU0025"
        }
    ]
).to_dict()

In [ ]:
print(online_features)

{'student_id': ['STU0025'], 'curriculum_problem_solving_score': [79.69999694824219], 'attendance_percent': [95.5], 'total_experience': [8], 'programming_language_encoded': [4], 'project_count': [5], 'certification_count': [0], 'curriculum_dsa_score': [94.69999694824219], 'curriculum_communication_score': [62.79999923706055], 'employability_score': [95.13999938964844], 'average_skill_gap': [1.159999966621399], 'curriculum_devops_score': [78.19999694824219], 'curriculum_dbms_score': [92.69999694824219], 'curriculum_cloud_score': [92.5], 'internship_count': [3], 'hackathon_count': [0], 'target_role_encoded': [4], 'cgpa': [7.150000095367432], 'curriculum_web_development_score': [94.69999694824219], 'gender_encoded': [1], 'curriculum_cybersecurity_score': [79.5], 'overall_skill_alignment': [98.83999633789062], 'curriculum_ai_ml_score': [92.0], 'university_encoded': [5], 'average_curriculum_skill': [85.52999877929688], 'curriculum_programming_score': [88.5]}

In [ ]:
online_df = pd.DataFrame(
    online_features
)

display(online_df)

,student_id,curriculum_problem_solving_score,attendance_percent,total_experience,programming_language_encoded,project_count,certification_count,curriculum_dsa_score,curriculum_communication_score,employability_score,...,target_role_encoded,cgpa,curriculum_web_development_score,gender_encoded,curriculum_cybersecurity_score,overall_skill_alignment,curriculum_ai_ml_score,university_encoded,average_curriculum_skill,curriculum_programming_score
0,STU0025,79.699997,95.5,8,4,5,0,94.699997,62.799999,95.139999,...,4,7.15,94.699997,1,79.5,98.839996,92.0,5,85.529999,88.5

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
final_model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

final_model.fit(
    X,
    y
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [ ]:
X_online = online_df[
    feature_columns
]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
prediction = final_model.predict(
    X_online
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
if prediction[0] == 1:
    print("Predicted placement status: Placed")
else:
    print("Predicted placement status: Not Placed")

Predicted placement status: Placed

In [ ]:
online_features = store.get_online_features(
    features=feature_service,
    entity_rows=[
        {"student_id": "STU0010"},
        {"student_id": "STU0020"},
        {"student_id": "STU0030"},
        {"student_id": "STU0040"}
    ]
).to_dict()

In [ ]:
online_df = pd.DataFrame(
    online_features
)

display(online_df)

,student_id,curriculum_problem_solving_score,attendance_percent,total_experience,programming_language_encoded,project_count,certification_count,curriculum_dsa_score,curriculum_communication_score,employability_score,...,target_role_encoded,cgpa,curriculum_web_development_score,gender_encoded,curriculum_cybersecurity_score,overall_skill_alignment,curriculum_ai_ml_score,university_encoded,average_curriculum_skill,curriculum_programming_score
0,STU0010,80.699997,83.500000,3,0,3,1,79.400002,82.900002,74.680000,...,1,8.00,62.500000,0,74.800003,98.720001,92.000000,1,75.849998,63.000000
1,STU0020,81.500000,81.900002,5,3,3,4,82.099998,71.000000,85.470001,...,5,7.24,76.199997,0,83.599998,97.989998,64.500000,2,77.010002,87.300003
2,STU0030,75.699997,81.699997,2,3,1,2,76.900002,82.599998,73.680000,...,5,6.87,82.800003,1,63.400002,96.080002,63.799999,4,68.150002,61.299999
3,STU0040,80.199997,83.699997,4,2,2,1,72.699997,58.099998,78.519997,...,3,7.48,75.199997,0,75.500000,97.760002,71.099998,2,73.540001,72.800003

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
online_df["predicted_placement"] = (
    final_model.predict(
        online_df[feature_columns]
    )
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
online_df["predicted_placement_status"] = (
    online_df["predicted_placement"]
    .map({
        0: "Not Placed",
        1: "Placed"
    })
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
display(
    online_df[
        [
            "student_id",
            "predicted_placement_status"
        ]
    ]
)

  student_id predicted_placement_status
0    STU0010                     Placed
1    STU0020                     Placed
2    STU0030                     Placed
3    STU0040                     Placed

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)